/**
 * Centralized WildShield AI Species & Taxonomy Mapping
 * Conforms to the WildShield AI Animal Behaviour & Farm Impact Knowledge Base.
 * Shared across all frontend tabs, Digital Twin, and Right Panel.
 * Aligns 1:1 with YOLOv11 trained weights best.pt (model.names).
 */

export const SPECIES_TAXONOMY = {
  0: {
    id: 0,
    class: "Wild Boar",
    code: "WS-WL-WB",
    domain: "Wildlife",
    threat: "HIGH",
    threatScore: 92,
    riskLevel: "CRITICAL",
    farmThreat: "🔴 High",
    intrusion: true,
    emoji: "🐗",
    scientific: "Sus scrofa",
    activityPeriod: "Crepuscular / Nocturnal (Late evening & night peak)",
    socialBehavior: "Groups / Sounders (Females & piglets); Solitary mature males",
    diet: "Omnivorous (Tubers, roots, fallen fruit, standing grains, maize)",
    farmDamage: "Rooting soil & tubers, consuming grains/fruits, severe physical crop disturbance & repeat raiding",
    damageCategory: "Direct crop consumption + soil excavation + trampling",
    safetyRisk: "Moderate — Aggressive if cornered with young",
    responses: ["Siren", "Floodlight"],
    actuators: { siren: true, floodlight: true, speaker: true, sprinkler: false },
    responsePolicy: "Wild Boar ↓ Geofence = TRUE ↓ High Threat ↓ Siren + Floodlight ↓ Farmer Alert",
    fallbackImage: "/ed-van-duijn-414NZVxzc20-unsplash.jpg"
  },
  1: {
    id: 1,
    class: "Nilgai",
    code: "WS-WL-NG",
    domain: "Wildlife",
    threat: "HIGH",
    threatScore: 84,
    riskLevel: "HIGH",
    farmThreat: "🔴 High",
    intrusion: true,
    emoji: "🐂",
    scientific: "Boselaphus tragocamelus",
    activityPeriod: "Early Morning & Late Afternoon (Peak feeding windows)",
    socialBehavior: "Herds of 10+ individuals; High vision & hearing sensitivity",
    diet: "Herbivore (Grasses, cereals, pulses, vegetables, shoots)",
    farmDamage: "Direct grazing of standing cereals/pulses, extensive crop trampling, dung pellet fouling",
    damageCategory: "Cereal & pulse crop loss + structural trampling",
    safetyRisk: "Low–Medium — High flight distance, rapid escape",
    responses: ["Floodlight", "Alarm"],
    actuators: { siren: false, floodlight: true, speaker: true, sprinkler: false },
    responsePolicy: "Nilgai ↓ Geofence = TRUE ↓ High Threat ↓ Floodlight + Directional Alarm ↓ App Alert",
    fallbackImage: "https://images.unsplash.com/photo-1589656966895-2f33e7653819?q=80&w=300&auto=format&fit=crop"
  },
  2: {
    id: 2,
    class: "Spotted Deer",
    code: "WS-WL-SD",
    domain: "Wildlife",
    threat: "MEDIUM",
    threatScore: 58,
    riskLevel: "WARNING",
    farmThreat: "🟠 Medium",
    intrusion: true,
    emoji: "🦌",
    scientific: "Axis axis",
    activityPeriod: "Crepuscular / Variable daytime foraging",
    socialBehavior: "Herd-forming (Female-young groups & male bachelor herds)",
    diet: "Herbivore (Primary: Grasses, tender crop shoots, flowers, fallen fruit)",
    farmDamage: "Grazing losses on young shoots, boundary trampling, localized crop consumption",
    damageCategory: "Herbaceous grazing loss + localized trampling",
    safetyRisk: "Low — Panic response triggered by loud noise",
    responses: ["Floodlight", "Alarm"],
    actuators: { siren: false, floodlight: true, speaker: true, sprinkler: false },
    responsePolicy: "Spotted Deer ↓ Geofence ↓ Medium Threat ↓ Soft Floodlight + Alarm (Avoid siren panic)",
    fallbackImage: "https://images.unsplash.com/photo-1484406566174-9da000fda645?q=80&w=300&auto=format&fit=crop"
  },
  3: {
    id: 3,
    class: "Rhesus Macaque",
    code: "WS-WL-RM",
    domain: "Wildlife",
    threat: "HIGH",
    threatScore: 82,
    riskLevel: "HIGH",
    farmThreat: "🔴 High",
    intrusion: true,
    emoji: "🐒",
    scientific: "Macaca mulatta",
    activityPeriod: "Diurnal (Full daylight orchard & canopy raiding)",
    socialBehavior: "Highly social troops; Rapid tree-to-ground transit & scout behavior",
    diet: "Omnivorous (Fruits, vegetables, tubers, grain ears, tender leaves)",
    farmDamage: "Fruit plucking, breaking stems & branches, wasteful feeding, repeated group raids",
    damageCategory: "Orchard fruit loss + vegetable destruction + group raiding",
    safetyRisk: "Moderate — Troop intimidation behavior",
    responses: ["Sprinkler", "Warning"],
    actuators: { siren: false, floodlight: false, speaker: false, sprinkler: true },
    responsePolicy: "Macaque Troop ↓ Geofence ↓ High Threat ↓ Sprinkler Guard + Distress Acoustic Call ↓ Farmer Alert",
    fallbackImage: "https://images.unsplash.com/photo-1540573133985-87b6da6d54a9?q=80&w=300&auto=format&fit=crop"
  },
  4: {
    id: 4,
    class: "Langur",
    code: "WS-WL-LG",
    domain: "Wildlife",
    threat: "MEDIUM",
    threatScore: 65,
    riskLevel: "MODERATE",
    farmThreat: "🟠 Medium–High",
    intrusion: true,
    emoji: "🐒",
    scientific: "Semnopithecus entellus",
    activityPeriod: "Diurnal (Morning & late afternoon summer peaks)",
    socialBehavior: "Troops ranging from 10 to 100+ individuals; Arboreal & terrestrial",
    diet: "Herbivore / Folivore (Leaves, blossoms, wild fruits, tender vegetables)",
    farmDamage: "Leaf stripping, canopy fruit consumption, boundary fence disruption",
    damageCategory: "Leaf & blossom damage + vegetable consumption",
    safetyRisk: "Low — High agility, retreats into upper canopy",
    responses: ["Sprinkler", "Warning"],
    actuators: { siren: false, floodlight: false, speaker: false, sprinkler: true },
    responsePolicy: "Langur Troop ↓ Geofence ↓ Medium Threat ↓ Visual Flash + Sprinkler Deterrent",
    fallbackImage: "https://images.unsplash.com/photo-1540573133985-87b6da6d54a9?q=80&w=300&auto=format&fit=crop"
  },
  5: {
    id: 5,
    class: "Gaur",
    code: "WS-WL-GR",
    domain: "Wildlife",
    threat: "CRITICAL",
    threatScore: 98,
    riskLevel: "CRITICAL",
    farmThreat: "🔴 Very High",
    intrusion: true,
    emoji: "🦬",
    scientific: "Bos gaurus",
    activityPeriod: "Morning/Evening feeding, afternoon resting; Nocturnal in disturbed zones",
    socialBehavior: "Herd-forming; Massive bovine weight (600–1000 kg)",
    diet: "Herbivore (Coarse grasses, bamboo shoots, forbs, agricultural crops)",
    farmDamage: "Severe crop consumption, boundary fence flattening, structural property damage",
    damageCategory: "Heavy biomass consumption + fence destruction + human safety threat",
    safetyRisk: "EXTREME — Do NOT approach, corner, or chase. Dangerous if threatened",
    responses: ["Siren", "Floodlight"],
    actuators: { siren: true, floodlight: true, speaker: true, sprinkler: true },
    responsePolicy: "Gaur ↓ Geofence = TRUE ↓ Very High Threat ↓ Do NOT approach ↓ Non-contact deterrent ↓ Immediate Authority Alert",
    fallbackImage: "https://images.unsplash.com/photo-1553531384-cc64ac80f931?q=80&w=300&auto=format&fit=crop"
  },
  6: {
    id: 6,
    class: "Cattle",
    code: "WS-DM-CT",
    domain: "Domestic",
    threat: "LOW",
    threatScore: 28,
    riskLevel: "LOW",
    farmThreat: "🟡 Medium",
    intrusion: false,
    emoji: "🐄",
    scientific: "Bos taurus",
    activityPeriod: "Mostly daytime grazing & resting",
    socialBehavior: "Domestic herd-oriented (Stray / escaped livestock)",
    diet: "Herbivore (Grasses, crop foliage, stubble)",
    farmDamage: "Casual grazing on young crops, minor trampling, boundary passage",
    damageCategory: "Grazing on standing foliage + boundary drift",
    safetyRisk: "Negligible — Docile domestic livestock",
    responses: ["Sprinkler", "Warning"],
    actuators: { siren: false, floodlight: false, speaker: true, sprinkler: true, buzzer: true },
    responsePolicy: "Cattle Detected ↓ Domestic Discrimination ↓ Low Threat ↓ Sprinkler / Warning Buzzer (Siren Bypassed)",
    fallbackImage: "https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?q=80&w=300&auto=format&fit=crop"
  },
  7: {
    id: 7,
    class: "Goat",
    code: "WS-DM-GT",
    domain: "Domestic",
    threat: "LOW",
    threatScore: 20,
    riskLevel: "LOW",
    farmThreat: "🟢 Low–Medium",
    intrusion: false,
    emoji: "🐐",
    scientific: "Capra hircus",
    activityPeriod: "Daytime grazing & browsing",
    socialBehavior: "Herd-forming domestic browsers",
    diet: "Herbivore (Shrubs, leaves, young crop seedlings)",
    farmDamage: "Nibbling young seedlings, leaf browsing, localized boundary grazing",
    damageCategory: "Seedling browsing + leaf consumption",
    safetyRisk: "Negligible",
    responses: ["Warning"],
    actuators: { siren: false, floodlight: false, speaker: false, sprinkler: false, buzzer: true },
    responsePolicy: "Goat Detected ↓ Domestic Discrimination ↓ Low Threat ↓ Local Beep Buzzer ↓ Farmer Check",
    fallbackImage: "https://images.unsplash.com/photo-1524024973431-2ad916746881?q=80&w=300&auto=format&fit=crop"
  },
  8: {
    id: 8,
    class: "Human",
    code: "WS-HM-HU",
    domain: "Human",
    threat: "ALERT",
    threatScore: 15,
    riskLevel: "ALERT",
    farmThreat: "⚠️ Context-dependent",
    intrusion: false,
    emoji: "🚶",
    scientific: "Homo sapiens",
    activityPeriod: "Day / Night (Farm workers, owners, researchers, trespassers)",
    socialBehavior: "Individual or groups",
    diet: "N/A",
    farmDamage: "N/A (Safety & context monitoring class)",
    damageCategory: "Safety monitoring + false positive mitigation",
    safetyRisk: "Critical Safety Rule: Never activate automated wildlife deterrents on humans",
    responses: ["Security Alert"],
    actuators: { siren: false, floodlight: false, speaker: false, sprinkler: false },
    responsePolicy: "Human Detected ↓ Wildlife Deterrence INHIBITED ↓ Log Context & Timestamp ↓ App Push Notification",
    fallbackImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=300&auto=format&fit=crop"
  },
  9: {
    id: 9,
    class: "Vehicle",
    code: "WS-VH-CV",
    domain: "Vehicle",
    threat: "SAFE",
    threatScore: 5,
    riskLevel: "SAFE",
    farmThreat: "⚠️ Context-dependent",
    intrusion: false,
    emoji: "🚜",
    scientific: "Automobile / Tractor",
    activityPeriod: "Any time (Tractors, road traffic, farm trucks)",
    socialBehavior: "N/A (Motion sensor trigger discrimination)",
    diet: "N/A",
    farmDamage: "N/A (Background discrimination class)",
    damageCategory: "Sensor trigger discrimination (Headlights, shadows, dust)",
    safetyRisk: "None",
    responses: ["Log Only"],
    actuators: { siren: false, floodlight: false, speaker: false, sprinkler: false },
    responsePolicy: "Vehicle Detected ↓ No Wildlife Deterrence ↓ Log Telemetry ↓ Continue Monitoring",
    fallbackImage: "https://images.unsplash.com/photo-1508974239320-0a029497e820?q=80&w=300&auto=format&fit=crop"
  }
};

export function getSpeciesMetadataByName(className) {
  if (!className) return null;
  const nameNorm = className.trim().toLowerCase();

  for (const key in SPECIES_TAXONOMY) {
    const item = SPECIES_TAXONOMY[key];
    if (item.class.toLowerCase() === nameNorm) return item;
  }

  // Fuzzy fallback
  for (const key in SPECIES_TAXONOMY) {
    const item = SPECIES_TAXONOMY[key];
    if (nameNorm.includes(item.class.toLowerCase()) || item.class.toLowerCase().includes(nameNorm)) {
      return item;
    }
  }

  // Elephant fallback for existing demo tour
  if (nameNorm.includes("elephant")) {
    return {
      id: 99,
      class: "Elephant",
      code: "WS-WL-EL",
      domain: "Wildlife",
      threat: "HIGH",
      threatScore: 96,
      riskLevel: "CRITICAL",
      farmThreat: "🔴 High",
      intrusion: true,
      emoji: "🐘",
      scientific: "Elephas maximus",
      activityPeriod: "Nocturnal & Crepuscular (Night grazing along forest fringe)",
      socialBehavior: "Matriarchal breeding herds & solitary bull groups",
      diet: "Herbivore (Sugarcane, banana, paddy, maize, cotton shoots)",
      farmDamage: "Severe standing crop trampling, tree pushing, biomass depletion, fence destruction",
      damageCategory: "Massive crop consumption + fence destruction + village safety risk",
      safetyRisk: "CRITICAL — High human-wildlife conflict hazard; Avoid high-volume sirens near villages",
      responses: ["Siren", "Floodlight", "Speaker"],
      actuators: { siren: true, floodlight: true, speaker: true, sprinkler: true },
      responsePolicy: "Elephant ↓ Geofence = TRUE ↓ Directional Strobe + Speaker ↓ Avoid Village Panic Siren ↓ Forest Dept Alert",
      fallbackImage: "/christoffer-brus-7hGF4emWkXs-unsplash.jpg"
    };
  }

  return {
    id: 999,
    class: className,
    code: "WS-WL-UN",
    domain: "Wildlife",
    threat: "LOW",
    threatScore: 30,
    riskLevel: "WARNING",
    farmThreat: "🟡 Monitored",
    intrusion: false,
    emoji: "🐾",
    scientific: "Wildlife Specimen",
    activityPeriod: "Variable",
    socialBehavior: "Unknown",
    diet: "Omnivorous / Herbivore",
    farmDamage: "Perimeter boundary activity monitored",
    damageCategory: "Perimeter exploration",
    safetyRisk: "Standard caution",
    responses: ["Warning"],
    actuators: { siren: false, floodlight: false, speaker: false, sprinkler: false },
    responsePolicy: "Unidentified Target ↓ Log Frame ↓ App Alert ↓ Passive Monitoring",
    fallbackImage: "https://images.unsplash.com/photo-1540573133985-87b6da6d54a9?q=80&w=300&auto=format&fit=crop"
  };
}
